name: practica-3-jose-zuniga-ga
run-name: ${{ github.actor }} has created this action for his fullstack Master
on:
  push:
    branches:
      - master
jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pruebas de SAST
        run: |
          echo "Ejecucion de pruebas de SAST"

      - name: Workspace path
        run: |
          echo "Path: ${{ github.workspace }}"

      - name: Create credentials file
        env:
          USERNAME: "${{ secrets.USERNAME }}"
          PASSWORD: "${{ secrets.PASSWORD }}"
        run: |
          apt-get update -q
          apt-get install -y gettext        
          envsubst < credentials.ini.tpl > credentials.ini
          cat credentials.ini

      - name: Upload Credential file
        uses: actions/upload-artifact@v2
        with:
          name: credentials
          path: credentials.ini
          

      - name: Build docker image
        run: |
          docker build -t devops_ws . --tag devops_ws_:$(date +%s)
